# fly.toml app configuration file generated for forex-horizon-wandering-frog-37 on 2024-12-21T22:07:01-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'forex-horizon-wandering-frog-37'
primary_region = 'sea'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
